### ISSUE TITLE
Enchanted spell turret crashes the game  (Touch spell, revolving contraption)

### ISSUE THREAD

**Issue by Griffures** [baileyholl/Ars-Creo#2]
## Version

**Minecraft** : *1.18.2*
**Ars Creo** : *1.0.2*

Played on **FTB Plexiglass Mountain** version *1.1.1* with **Create** version *0.4.1*.

## How to reproduce the bug

Please see the screenshots [here on imgur](https://imgur.com/a/lqV1NqO).

## Crash log

Exception raised :
> java.lang.NoSuchMethodError: 'void com.hollingsworth.arsnouveau.api.spell.EntitySpellResolver.onCastOnBlock(net.minecraft.world.phys.BlockHitResult, net.minecraft.world.entity.LivingEntity)'

Full crash report [on pastebin](https://pastebin.com/ygjDtN1w).

**Comment by baileyholl** [comment]
Update to latest create and ars creo
